### PR TITLE
Bug 1915473: Annotate manifests for single-node-developer cluster profile

### PR DESCRIPTION
**Pull request by guillaumerose**
This implements phase 1 of openshift/enhancements#482

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
@guillaumerose: apologies for the late review.

Could you please rebase your PR and include the files introduced in https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/62?

**Comment by guillaumerose** [comment]
@bertinatto done thanks!

**Comment by bertinatto** [comment]
> @bertinatto done thanks!

@guillaumerose I don't see the annotation in `manifests/09_webhook_config.yaml` for example. Isn't it necessary there?

**Comment by guillaumerose** [comment]
Thanks I didn't see the new file. I included all files now.

**Review by bertinatto — COMMENTED** [review]
/lgtm
/approve

**Comment by guillaumerose** [comment]
rebased

**Comment by cfergeau** [comment]
The `ci/prow/verify` failure should be fixable with `make update-bindata`

**Pull request merged**
