### PR TITLE
STOR-1443: Restart webhook Pods if `csi-snapshot-webhook-secret` changed

### PR DESCRIPTION
**Pull request by mpatlasov**
Adding `WithSecretHashAnnotationHook()` for `csi-snapshot-webhook-secret` ensures that new annotation is published in `csi-snapshot-webhook` Deployment. This, in turn, leads to webhook pods restart.

### CODE REVIEW

**Comment by Phaow** [comment]
Pre verifiy passed with the pre merged build `4.14.0-0.ci.test-2023-08-16-025118-ci-ln-3qics72-latest`, but the CI results looks not healthy. Looks some hypershift config check failed.

```console
# After the csi-snapshot-webhook-secret secret changed, driver controller restarted
$ oc delete secret csi-snapshot-webhook-secret
secret "csi-snapshot-webhook-secret" deleted

$ oc get po -l app=azure-file-csi-driver-controller -w
oc get po -l app=csi-snapshot-webhook -w
NAME                                    READY   STATUS    RESTARTS   AGE
csi-snapshot-webhook-79bc7b44bc-8fm59   1/1     Running   0          171m
csi-snapshot-webhook-79bc7b44bc-hb6vq   1/1     Running   0          171m
csi-snapshot-webhook-79bc7b44bc-8fm59   1/1     Terminating   0          171m
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Pending       0          0s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Pending       0          0s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     ContainerCreating   0          0s
csi-snapshot-webhook-79bc7b44bc-8fm59   0/1     Terminating         0          171m
csi-snapshot-webhook-79bc7b44bc-8fm59   0/1     Terminating         0          171m
csi-snapshot-webhook-79bc7b44bc-8fm59   0/1     Terminating         0          171m
csi-snapshot-webhook-79bc7b44bc-8fm59   0/1     Terminating         0          171m
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Terminating         0          1s
csi-snapshot-webhook-7b8dcc4867-4n2ft   0/1     Pending             0          0s
csi-snapshot-webhook-7b8dcc4867-4n2ft   0/1     Pending             0          0s
csi-snapshot-webhook-7b8dcc4867-4n2ft   0/1     ContainerCreating   0          0s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Terminating         0          2s
csi-snapshot-webhook-c54f8fb7c-x47bs    1/1     Terminating         0          2s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Terminating         0          3s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Terminating         0          3s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Terminating         0          3s
csi-snapshot-webhook-c54f8fb7c-x47bs    0/1     Terminating         0          3s
csi-snapshot-webhook-7b8dcc4867-4n2ft   0/1     ContainerCreating   0          3s
csi-snapshot-webhook-7b8dcc4867-4n2ft   1/1     Running             0          3s
csi-snapshot-webhook-79bc7b44bc-hb6vq   1/1     Terminating         0          171m
csi-snapshot-webhook-7b8dcc4867-b67wj   0/1     Pending             0          0s
csi-snapshot-webhook-7b8dcc4867-b67wj   0/1     Pending             0          0s
csi-snapshot-webhook-7b8dcc4867-b67wj   0/1     ContainerCreating   0          0s
csi-snapshot-webhook-79bc7b44bc-hb6vq   0/1     Terminating         0          171m
csi-snapshot-webhook-79bc7b44bc-hb6vq   0/1     Terminating         0          171m
csi-snapshot-webhook-79bc7b44bc-hb6vq   0/1     Terminating         0          171m
csi-snapshot-webhook-79bc7b44bc-hb6vq   0/1     Terminating         0          171m
csi-snapshot-webhook-7b8dcc4867-b67wj   0/1     ContainerCreating   0          2s
csi-snapshot-webhook-7b8dcc4867-b67wj   1/1     Running             0          2s

$ oc get po -l app=csi-snapshot-webhook
NAME                                    READY   STATUS    RESTARTS   AGE
csi-snapshot-webhook-7b8dcc4867-4n2ft   1/1     Running   0          2m23s
csi-snapshot-webhook-7b8dcc4867-b67wj   1/1     Running   0          2m20s

```

**Comment by mpatlasov** [comment]
/hold
This PR needs https://github.com/openshift/hypershift/pull/2915 to be merged first.

**Comment by mpatlasov** [comment]
Update: `ci/prow/e2e-hypershift-conformance` failed for real. If `isHyperShift`, the informer (`secretInformer`) must use kubeClient for control plane:
```
	var secretInformer informercorev1.SecretInformer
	if isHyperShift {
		secretInformer = controlPlaneInformersForNamespaces.InformersFor(controlPlaneNamespace).Core().V1().Secrets()
	} else {
		secretInformer = guestKubeInformersForNamespaces.InformersFor(controlPlaneNamespace).Core().V1().Secrets()
	}
```

**Comment by mpatlasov** [comment]
> /label jira/valid-bug

@Phaow , this PR is too late for 4.14, it will go to 4.15 in the scope of new Epic (https://issues.redhat.com/browse/STOR-1445)

**Comment by Phaow** [comment]
@mpatlasov Thanks for the info! Just wonder the `tide` shows we missed the `jira/valid-bug` label. From my understanding, all the lables added just currently the master branch switch to sync the `release-4.15`, it should able to merge to master(release-4.15). Not sure why it is not merged.

**Comment by mpatlasov** [comment]
> From my understanding, all the lables added just currently the master branch switch to sync the release-4.15, it should able to merge to master(release-4.15). Not sure why it is not merged.

@Phaow My understanding is that 4.14 was not branched yet. This means that such a commit, if merged, would come to master that will become 4.14 soon. Such merges are limited by `jira/valid-bug` label now. (There was an email a few days ago explaining why 4.14 was not branched, and I have not seen any update follow-up to that email)

**Comment by Phaow** [comment]
@mpatlasov Good to know. Thanks for clarifying! Sorry seems I missed the e-mail details, make sense.

**Pull request merged**
