### PR TITLE
Bug 1797694: Add unit tests

### PR DESCRIPTION
**Pull request by jsafrane**
\+ add lot of vendored files (`go mod tidy` + `go mod vendor`).

Please check the tests carefully! Is there an easier way, how to run `sync()` with some objects and check that it modified / created the objects in the right way?

There are still some tests missing.

sync.go is at 82% statement coverage. operator.go has 44%. Perhaps we should move whole `sync()` into sync.go to get stats without the operator boilerplate and event processing.

### CODE REVIEW

**Comment by huffmanca** [comment]
I've looked through the test, and everything here makes sense to me. I would have thought that we could test the different sync methods for the CRDs/Deployments separately; however, considering that we can test both of this by calling the Operator's `sync` as you're doing.

As far as moving `sync` (and related functions) itself into `sync.go` - I wouldn't be opposed.

**Comment by jsafrane** [comment]
/hold
for rebase

**Comment by jsafrane** [comment]
/hold cancel
rebase finished

**Pull request merged**
