### PR TITLE
Bug 2037856: Update library-go to get leader election updates

### PR DESCRIPTION
**Pull request by jsafrane**
* Get ConfigMap + Lease leader election in 4.10 from openshift/library-go#1282.
* And get improved WebhookConfig creation/update from https://github.com/openshift/library-go/pull/1293
* Update snapshot-controller RBAC rules, [it needs to patch snapshot objects](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v5.0.1).

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for fixes in ApplyValidatingWebhookConfiguration  https://github.com/openshift/library-go/pull/1293

**Comment by jsafrane** [comment]
/hold

```
event happened 34 times, something is wrong: ns/openshift-cluster-storage-operator deployment/csi-snapshot-controller-operator - reason/ValidatingWebhookConfigurationUpdated Updated ValidatingWebhookConfiguration.admissionregistration.k8s.io/snapshot.storage.k8s.io because it changed
 ```

**Comment by bertinatto** [comment]
> /hold
> 
> `event happened 34 times, something is wrong: ns/openshift-cluster-storage-operator deployment/csi-snapshot-controller-operator - reason/ValidatingWebhookConfigurationUpdated Updated ValidatingWebhookConfiguration.admissionregistration.k8s.io/snapshot.storage.k8s.io because it changed`

@jsafrane can you bump library-go again? https://github.com/openshift/library-go/pull/1294

**Comment by jsafrane** [comment]
Updated library-go again to get https://github.com/openshift/library-go/pull/1294

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
