### PR TITLE
STOR-1700: Fix: typo of volumegroupsnapshots

### PR DESCRIPTION
**Pull request by Phaow**
### [STOR-1700](https://issues.redhat.com//browse/STOR-1700): Fix: typo of volumegroupsnapshots
- typo `volumegroupnapshots` missed `s` in snapshot, though it has no impact to function, we'd better correct it.

cc to @bertinatto @duanwei33

### CODE REVIEW

**Comment by Phaow** [comment]
/label qe-approved
Pre verify passed with pre merged build `4.16.0-0.test-2024-02-18-063125-ci-ln-9b6fvzb-latest` (`build 4.16,openshift/cluster-csi-snapshot-controller-operator#195`), just a typo fix no impact to origin codes logic
- Install a cluster check cluster snapshot operator is healthy and the `volumegroupsnapshot` is not enabled by default.
```console
$ oc get crd| grep volumegroupsnapshot
```
- Enable the feature gate, checked the `volumegroupsnapshot` crd created as expected, and the args added to the `csi-snapshot-webhook` and `csi-snapshot-controller`.
```console
$ oc get crd| grep volumegroupsnapshot
volumegroupsnapshotclasses.groupsnapshot.storage.k8s.io           2024-02-18T12:48:36Z
volumegroupsnapshotcontents.groupsnapshot.storage.k8s.io          2024-02-18T12:48:35Z
volumegroupsnapshots.groupsnapshot.storage.k8s.io                 2024-02-18T12:48:35Z
$ oc get deploy/csi-snapshot-webhook -oyaml| grep 'enable-volume-group'
        - --enable-volume-group-snapshot-webhook
$ oc get deploy/csi-snapshot-controller -oyaml| grep 'enable-volume-group'
        - --enable-volume-group-snapshots
```

**Review by mpatlasov — APPROVED** [review]

**Pull request merged**
