### PR TITLE
Bug 1992255: Fix leader election defaults in snapshot-controller

### PR DESCRIPTION
**Pull request by bertinatto**
Current leader election defaults cause pod restarts when apiserver is unavailable for longer than 60 seconds. The values set in this patch come from https://github.com/openshift/library-go/blob/master/pkg/config/leaderelection/leaderelection.go.

Also, this patchset bump some libraries for OCP 4.9 release: kube libraries, openshift/library-go, openshift/api, snapshotter client among others.

Besides that, I'm removing go-bindata dependency that's no longer used since we're now using the `embed` built-in package.

CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
some problem with registry?

**Comment by bertinatto** [comment]
/hold
wait for or https://github.com/openshift/csi-external-snapshotter/pull/56

**Comment by bertinatto** [comment]
/hold cancel
https://github.com/openshift/csi-external-snapshotter/pull/56 merged.

**Pull request merged**
