### PR TITLE
WIP Bug 1826230: Bump to kube 1.18.2

### PR DESCRIPTION
**Pull request by marun**
/cc @sttts @mfojtik

### CODE REVIEW

**Comment by marun** [comment]
I attempted this bump in aid of updating to use a revised ApplyDeployment (https://bugzilla.redhat.com/show_bug.cgi?id=1827050), but it doesn't appear that github.com/kubernetes-csi/external-snapshotter has a 1.18-compatible release yet.

**Comment by jsafrane** [comment]
Hey, thanks for bumping the library-go for us!

> it doesn't appear that github.com/kubernetes-csi/external-snapshotter has a 1.18-compatible release yet.

You're correct, external-snapshotter is usually released after Kubernetes release.

I'm tempted to leave the library-go as it is and cherry-pick only the `ApplyDeployment` changes. From what you've seen, does this operator need any other library-go fixes?

cc @openshift/storage

**Comment by marun** [comment]
> I'm tempted to leave the library-go as it is and cherry-pick only the `ApplyDeployment` changes. From what you've seen, does this operator need any other library-go fixes?

I'm not sure any of the library-go fixes are required, I was just trying to update to the version of kube we're shipping in 4.5.

**Comment by jsafrane** [comment]
Upstream is not going to release a new snapshot API before 4.5 code freeze. We'll stick to  client-go from Kubernetes 1.17.

/close

**Pull request closed without merging**
