### PR TITLE
[CNF-5646] add capability annotation

### PR DESCRIPTION
**Pull request by qJkee**
Add capability annotation to the manifests which allows to
disable operator and components via configuration

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
I can see only CSI snapshot tests failed (which is good), but openshift/api with [the API change](https://github.com/openshift/api/pull/1263) needs to be updated in CVO, so snapshots are installed by default.

**Comment by duanwei33** [comment]
With pre-merged PR, I followed the [OCP-54900](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-54900) to test and passed.

Not sure why several cases failed in CI, just rerun it.

/test e2e-aws

**Comment by brandisher** [comment]
The failures don't look related to this.

/retest

**Pull request merged**
