### PR TITLE
Use go:embed for static yaml files

### PR DESCRIPTION
**Pull request by jsafrane**
Move from bindata to go:embed.

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for https://github.com/openshift/library-go/pull/1117

**Comment by jsafrane** [comment]
/hold cancel
openshift/library-go#1117 is not needed. The whole operator should be updated to the new DeploymentController, but that should be a separate PR

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
