### PR TITLE
Bug 1876810: Bump external-snapshotter to v3.0.0

### PR DESCRIPTION
**Pull request by jsafrane**
- update to klog/v2
- bump library-go to the latest version
- bump kubernetes to the latest version
- bump go to 1.15
- bump external-snapshotter client to v3 (with import path change)
  - update CRD definitions from the external-snapshotter to `manifest/`
    - use `apiextensions/v1` instead of `v1beta1` as result

### CODE REVIEW

**Comment by jsafrane** [comment]
Unit tests are likely to fail due to github.com/openshift/library-go/pull/896

**Comment by jsafrane** [comment]
cc @openshift/storage

**Comment by jsafrane** [comment]
And https://github.com/openshift/release/pull/11992 is needed for new golang

**Comment by jsafrane** [comment]
/retest
with go 1.15

**Comment by jsafrane** [comment]
It builds \o/

**Comment by jsafrane** [comment]
/retest
flakes

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
